---
- hosts: all
  roles:
  # cli
  # shell tooling
  - role: arubdesu_git
    git_user_name: Allister Banks
    git_user_email: arubdesu@me.com
  roles:

- hosts: Allister11
  roles:
  # GUI
  # darn dock
  - role: arubdesu_dock
    dockutil_exe: /usr/local/bin/dockutil
    src_path: ~/Documents/dev
    apps:
    - /Applications/Launchpad.app
    - /Applications/3gChrome.app
    - /Applications/Preview.app
    - /Applications/CoRD.app
    - /Applications/TeamViewer.app
    - /Applications/Remote Desktop.app
    - /Applications/Screen Sharing.app
    - /Applications/Terminal.app
    - /Applications/Activity Monitor.app
    - /Applications/Safari.app
    - /Applications/TextMate.app
    - /Applications/TextExpander.app
    - /Applications/System Preferences.app
    folders:
    - path: '~/Downloads'
    - path: '~/Desktop'

- hosts: other
  roles:
  # GUI
  # bootstrappingApps
  - role: arubdesu_cask_package
    package_name: dropbox
  - role: arubdesu_cask_package
    package_name: onepassword
